[project]
name = "cumac"
version = "0.1.0"
description = "Write a .cu kernel, run it on macOS via tinygrad's NV runtime"
readme = "README.md"
authors = [
    { name = "Art Moskvin", email = "amoskvin@me.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.4",
    "tinygrad",
]

[project.scripts]
cumac = "cumac:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
tinygrad = { git = "https://github.com/tinygrad/tinygrad", rev = "235044c9d" }

[tool.ruff.lint]
ignore = ["E701"]
